Add Giftcards integration sample
adyen-examples/adyen-dotnet-online-payments pull request #72
Opened 2023-03-31 10:03 UTC by Kwok-he-Chu

2023-04-03 16:04 UTC, gcatanese requested changes
Good work!

I have added some specific comments (see review) and we should discuss the following:
- simplify the sample app using only the Gift Card component (no drop-in)?
- allow to apply the Gift Card only once?
- is it possible to customise Gift Card component: use `Redeem Gift Card` instead of `Add Gift Card`? use `Gift Card Number` instead of `Card Number`? Change validation message `Security code field is empty`?

2023-04-13 18:42 UTC, Kwok-he-Chu commented on giftcard-example/wwwroot/js/adyenGiftcardImplementation.js
> +        const paymentMethodsResponse = await callServer("/api/paymentMethods");
Resolved, decided to mount the individual components in their own containers. Now we no longer get the list of payment methods and resolve this dynamically

When mounting, a developer can use: https://docs.adyen.com/payment-methods/apple-pay/web-component#step-3-mount-the-component

```
applePayComponent
   .isAvailable()
   .then(() => {
       applePayComponent.mount("#applepay-container");
   })
   .catch(e => {
       //Apple Pay is not available
   });
```

2023-04-13 18:43 UTC, Kwok-he-Chu commented on giftcard-example/readme.md
> +![Card checkout demo](wwwroot/images/cardcheckout.gif)
I'll add the card animation once everything is approved (the frontend), please review. I'll make the GIF at the end of this week @gcatanese

2023-04-13 19:37 UTC, Kwok-he-Chu commented on giftcard-example/wwwroot/js/adyenGiftcardImplementation.js
> +function hideAllPaymentMethodButtons() {
Added a 'Go back'-button

2023-04-13 20:03 UTC, Kwok-he-Chu commented
Merge: https://github.com/adyen-examples/adyen-testing-suite/pull/31 to have the E2E tests run here @gcatanese

2023-04-14 07:15 UTC, gcatanese approved these changes

2023-04-14 07:18 UTC, gcatanese commented
@Kwok-he-Chu  Great work. I have committed a minor [edit](https://github.com/adyen-examples/adyen-dotnet-online-payments/pull/72/commits/9d4926d18b48d0539f7a2bc58019e4a37673e0cd) to display an example of GiftCard number (allow devs to copy-paste without leaving the app)

2023-04-14 11:54 UTC, merged